### PR TITLE
Uniformize configuration across plugins

### PR DESCRIPTION
**Pull request by obourdon**

### CODE REVIEW

**Comment by elemoine** [comment]
@obourdon does this fix an open issue?

**Comment by elemoine** [comment]
> @obourdon does this fix an open issue?

Ok, I see that there is an Issue for the disk plugin but not for the cpu plugin.

Patch looks good to me.

**Comment by marcin-krolik** [comment]
LGTM

**Comment by obourdon** [comment]
@intelsdi-x/snap-maintainers any chance to get this integrated soon ?

**Pull request merged**
