### PR TITLE
remove unused lines

### PR DESCRIPTION
**Pull request by ami-GS**

### CODE REVIEW

**Comment by marcin-krolik** [comment]
LGTM

**Comment by jcooklin** [comment]
@ami-GS will you rebase your PR with master and we will get it merged.  Thanks.

**Comment by ami-GS** [comment]
To remove os.Open in init() cancels proc existence validation committed in previous.
Is that ok?

**Comment by katarzyna-z** [comment]
@ami-GS could you rebase your code again and squash commits?

**Comment by mjbrender** [comment]
@jcooklin could you weigh in on @ami-GS's question above?

**Comment by IRCody** [comment]
>To remove os.Open in init() cancels proc existence validation committed in previous.
Is that ok?
@ami-GS: I'm unsure what this means. I think it would be easier to understand if you could rebase your changes on top of master so we just see your changes. Thanks!

**Comment by ami-GS** [comment]
Firstly I removed lines due to nonsense os.Open(path), because the return value is not used.
However I noticed the os.Open(path) is called for validation of file existence.
I think these lines are necessary to be here.
Sorry for trouble I caused.

**Comment by IRCody** [comment]
@ami-GS: Was just trying to understand what was going on. You didn't cause any trouble! Please feel free to contribute again if you see anything that needs to be done.

**Pull request closed without merging**
